// This file is auto-generated by @hey-api/openapi-ts

export type Post = {
    userId: number;
    id: number;
    title: string;
    body: string;
};

export type GetPostsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/posts';
};

export type GetPostsResponses = {
    /**
     * OK
     */
    200: Array<Post>;
};

export type GetPostsResponse = GetPostsResponses[keyof GetPostsResponses];

export type GetPostByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/posts/{id}';
};

export type GetPostByIdResponses = {
    /**
     * OK
     */
    200: Post;
};

export type GetPostByIdResponse = GetPostByIdResponses[keyof GetPostByIdResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};